### ISSUE TITLE
new mirror at mirrors.dotsrc.org (Denmark)

### ISSUE THREAD

**Issue by AndersTrier** [Antergos/antergos-packages#122]
Hi!

We host a mirror of Antergos at mirrors.dotsrc.org:
http://mirrors.dotsrc.org/antergos/
https://mirrors.dotsrc.org/antergos/
ftp://mirrors.dotsrc.org/antergos/
rsync://mirrors.dotsrc.org/antergos/
contact: staff@dotsrc.org
location: Aalborg University, Aalborg, Denmark
connection: 1Gbit
organization: dotsrc.org

We once every hour from rsync.mirrorservice.org. Please add us to your list of mirrors, and feel free to send some traffic our way.

Btw, are you sure you need us to use the "--ignore-times" rsync option? What is the reasoning behind this?
> -I, --ignore-times          don't skip files that match size and time

From a stackoverflow thread:
> --ignore-times means that rsync will checksum every file, even if the timestamps and file sizes match. This means it will synchronise more files than the default behaviour. It will include changes to files even where the file size is the same and the modification date/time has been reset to the original value (resetting the date/time is unlikely to be done in practise, but it could happen). Checksumming every file means it has to be entirely read from disk, which may be slow.

This seems unnecessary and cpu-intensive.

Best regards
Anders Trier Olesen
dotsrc.org

**Comment by lots0logs** [comment]
Thanks for joining our mirror network! :smile:  Regarding your question: Although its unlikely, it is possible to modify a file without affecting its size and then reset the last-modified time to what it was before the file was modified. Obviously that has security implications as well as data integrity implications which is why we use the `--ignore-times` option. Its also worth mentioning that the checksums are not generated by the receiver (your mirror), they are generated by the sender (the tier 1 mirror you are syncing from) so there's nothing to worry about in regards to CPU usage :wink:
