### ISSUE TITLE
Suggestion - add SiS video driver

### ISSUE THREAD

**Issue by artur9010** [Antergos/antergos-packages#160]
https://aur.archlinux.org/packages/xf86-video-sis/

**Comment by karasu** [comment]
Conflicts: 	X-ABI-VIDEODRV_VERSION<23, X-ABI-VIDEODRV_VERSION>=24, xorg-server<1.19 

I'm sorry, not working with xorg-server 1.9 is a no no for us.

**Comment by karasu** [comment]
Ups, I readed it wrong.

**Comment by Yoshi2889** [comment]
This is not compatible with the Xorg 1.19 stack, so we'd need to maintain the 1.18 or lower stack for this to work; I don't think it is worth the effort, really, to be honest.

The cards are generally very old and found in systems of the 32-bit era. Since we don't support 32-bit anymore I think it'd be safe to say that there aren't many, if any, users still using them.
