### ISSUE TITLE
antergos-gnome-meta > pamac tray is invisible on default GNOME installation.

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#274]
**pamac** tray do not work without topicons-plus and the package (topicons)  from Antergos-Repo do not work:

https://forum.antergos.com/compose?p=/topic/8763/antergos-gnome-17-12-missing-libs-right-after-fresh-install/27

What happens?

1. pamac tray is invisible on default GNOME installation.
1a. topicons-plus and chrome-gnome-shell is not installed by default GNOME installation!
2. installing topicons from Antergos-Repo and enable it
2a. still no pamac tray icon visible.
3. Uninstalling topicons package and use topicons-plus directly from gnome-shell-extensions side works without a problem!

**Comment by karasu** [comment]
There's something wrong with that package. I did confirm it a few days ago (so it should be available), but it hasn't been moved by the system /(it's still in the antergos staging repo).

staging repo version 1:21-1
normal repo version 1:20-1

@lots0logs please, can you fix this?

**Comment by killajoe** [comment]
21 is still not come into normal repo... updkg is from 17.9.2017:

`[ANTBS] | [updpkg] gnome-shell-extension-topicons ('20', '21')
 master
1 parent 8565a0e commit 9f4e717566aba159c6a10f500ded9b6a28713a59 @antbs antbs committed on 17 Sep 2017`

But also maintainer stops developing Topicons-Plus:

**This repository has been archived by the owner. It is now read-only.**

https://github.com/phocean/TopIcons-plus/issues/91

**Comment by killajoe** [comment]
As we mainly need this for pamac-tray-icon, may there is a possibillity to get it working without legacy-tray-icon?

**Comment by killajoe** [comment]
Manjaro uses this one: https://github.com/manjaro/packages-community/tree/master/gnome/gnome-shell-extension-manjaro-update

**Comment by karasu** [comment]
It's this one "rebranded": https://github.com/RaphaelRochet/arch-update

Added (will show Arch icons and not Antergos ones) here: https://github.com/Antergos/antergos-packages/commit/49a9e05f962005edc838dd8daf8e607a9527444c

Still on staging only. Needs testing.

**Comment by killajoe** [comment]
I see this too after cloning from manjaro...
I will try out, may I already see how to change icons😑

**Comment by killajoe** [comment]
still an issue ;)

**Comment by luisfpg** [comment]
Starting with GNOME 3.28, legacy tray support was completely dropped.
Also, topicons will not work again.
Ubuntu uses the appindicator extension: https://extensions.gnome.org/extension/615/appindicator-support/
Pamac already ships the `pamac-tray-appindicator` extension for KDE support.
Maybe a better option would be to enable that one for GNOME as well;
I did it by editing `/etc/xdg/autostart/pamac-tray.desktop` and `/etc/xdg/autostart/pamac-tray-appindicator.desktop` and just replaced KDE; by KDE;GNOME; in both `OnlyShowIn` and `NotShowIn`.
Of course, I think Antergos should ship the indicators extension by default instead of TopIconsPlus, as it is non-funcional nowadays anyway...

**Comment by killajoe** [comment]
nice find! i will check this!

**Comment by killajoe** [comment]
This is an very easy and working solution! thanks @luisfpg !!

* canging 
/etc/xdg/autostart/pamac-tray.desktop to do nopt show in Gnome

* installing `pamac-tray-appindicator`
and change 
/etc/xdg/autostart/pamac-tray-appindicator.desktop
to also start in GNOME

![pamac-tray-1](https://user-images.githubusercontent.com/16797647/39451404-e009651a-4cce-11e8-9db2-5bdc8b4026c3.png)

**Comment by luisfpg** [comment]
For a general replacement of the indicator extension over TopIconsPlus, there's a catch on applications that use electron, such as Skype, because of this bug: https://github.com/electron/electron/issues/10427
Electron uses a dummy way to check whether indicators are supported: testing the `XDG_CURRENT_DESKTOP` environment variable. If running on Unity, Pantheon, Ubuntu's GNOME or PopOS's GNOME, it enables indicators.
So, to make such applications work, one has to fool them by setting the proper environment variable. So, for example, I've made a copy of my `$HOME/.config/autostart/skypeforlinux.desktop` to some other name (because Skype will override it) and replaced the Exec line by this: `Exec=env XDG_CURRENT_DESKTOP=Unity /usr/bin/skypeforlinux`.
This way the icon is correctly shown.
I hope the electron bug can be resolved quickly, so no workarounds are needed for users to see the (ever growing list of) electron apps icons in the panel.
Other applications, such as Dropbox or Chromium show their icons as indicators out of the box.

**Comment by killajoe** [comment]
i would like to get this installed by default on Antergos Gnome setup :)

**Comment by luisfpg** [comment]
There is still another thing to consider when implementing this: KDE Plasma's implementation of StatusNotifierItem seems to be broader than the one in Unity / GNOME extension.
For example, in Plasma, a specific event is triggered on click, whereas in Unity / GNOME the menu is shown as well. If I'm not mistaken, in Plasma, when left-clicking the icon, Pamac opens with the Updates tab open, so they can be applied.
In GNOME extension, however, clicking brings up the menu, which has the menu items "Package manager" and "Quit" (maybe not exactly the same text because I use it in Portuguese). And clicking on "Package manager" opens Pamac in the standard install mode, not on updates.
So, I suggest to also add another item in the SNI's context menu to open Pamac in update mode already.
Otherwise, people would get confused on how to install the actual updates.

**Comment by killajoe** [comment]
yes i can see thios in gnome-shell left and right click on the icon open the menu

**Comment by killajoe** [comment]
> So, I suggest to also add another item in the SNI's context menu to open Pamac in update mode already.
Otherwise, people would get confused on how to install the actual updates.

can you make this more clear to me  ;)

**Comment by luisfpg** [comment]
> > So, I suggest to also add another item in the SNI's context menu to open Pamac in update mode already.
> 
> can you make this more clear to me ;)

There are 2 menu items when clicking the pamac indicator:

- Package manager
- Quit

Selecting "Package manager" opens pamac not in the Update model, but as if one would install another application.

My proposal is to have the following menu structure when there are updates available:

- Show updates
- Package manager
- Quit

So the user knows that right after clicking the first menu item, the available updates will be shown. BTW, in KDE, that is exactly what happens when clicking the icon (left clicking is not supported in Unity / GNOME extension - it just shows the menu as if one would have right clicked).

**Comment by killajoe** [comment]
Like This?
[Desktop Entry]
Name=Update Notifier Appindicator
Icon=update-notifier
Exec=env XDG_CURRENT_DESKTOP=Unity pamac-tray-appindicator
Terminal=false
Type=Application
StartupNotify=true
OnlyShowIn=GNOME;``

**Comment by luisfpg** [comment]
For pamac you don't need `env XDG_CURRENT_DESKTOP=Unity`

Would be something like:

**$HOME/.config/autostart/pamac-tray-appindicator.desktop**:
```desktop
[Desktop Entry]
Name=Update Notifier Appindicator
Icon=update-notifier
Exec=pamac-tray-appindicator
Terminal=false
Type=Application
StartupNotify=true
OnlyShowIn=KDE;GNOME
```

**$HOME/.config/autostart/pamac-tray.desktop**:
```desktop
[Desktop Entry]
Name=Update Notifier
Icon=update-notifier
Exec=sh -c "GDK_BACKEND=x11 pamac-tray"
Terminal=false
Type=Application
StartupNotify=false
NotShowIn=KDE;GNOME
```

**Comment by killajoe** [comment]
ah yes i got it... i do not get where the **menu** is edited.. i was thinking that the `XDG_CURRENT_DESKTOP` will give the gtk dialogues instead of the qt ones :(

![menu-pamac-appi](https://user-images.githubusercontent.com/16797647/40140781-10005422-5954-11e8-9d69-ce16361bb330.png)

**Comment by killajoe** [comment]
https://github.com/manjaro/pamac/blob/master/src/tray-appindicator.vala

**Comment by killajoe** [comment]
No package manager showing up to show available updates for default GNOME Desktop....
We should solve this.

**Comment by killajoe** [comment]
gnome-shell-extension-topicons-plus-git from [AUR](https://aur.archlinux.org/packages/gnome-shell-extension-topicons-plus-git/) is working nicely on a tryout at the moment....
so may merging this to build a package and adding it to GNOME desktop?

**Comment by killajoe** [comment]
but i see this today in tweaks -- extensions:
![bildschirmfoto vom 2019-01-31 10-34-49](https://user-images.githubusercontent.com/16797647/52066525-07953400-2579-11e9-8c6b-7894be49775d.png)
enable it and got this:
![pamac-app-indicator](https://user-images.githubusercontent.com/16797647/52066539-0fed6f00-2579-11e9-8379-d052351570ef.png)

**Comment by killajoe** [comment]
Not needed anymore as there is an extension for pamac tray icon on its own now...
This could be enabled by default on GNOME install ...
