### ISSUE TITLE
octopi needs gksu as dependency (but it has been moved to AUR)

### ISSUE THREAD

**Issue by karasu** [Antergos/antergos-packages#316]
```
LANG=C sudo pacman -S octopi
resolving dependencies...
warning: cannot resolve "gksu", a dependency of "octopi"
:: The following package cannot be upgraded due to unresolvable dependencies:
      octopi

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: octopi: requires gksu
```

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/79c5e20b5934b179f658b277ca4f2160712e74c9

**Comment by sum01** [comment]
@karasu I'd say don't bother with it & use the AUR's [octopi-git](https://aur.archlinux.org/packages/octopi-git/) since there hasn't been a new octopi tag since 2016. [~290 commits since the last release](https://github.com/aarnt/octopi/compare/v0.8.1...master) is a lot of bugfixes/features/improvements to be missing out on.
