### ISSUE TITLE
Lightdm-greeter screen security issue

### ISSUE THREAD

**Issue by dtschmitz** [Antergos/antergos-packages#32]
In troubleshooting the preceding issue (lock screen) for gnome-shell, I have discovered that while either the default panel Lock icon works or the 'custom keyboard shortcut' mapping super+L to dm-tools works, in either case, pressing "<ctrl>+F1" will cause an immediate return to the user session Desktop bypassing a password prompt entirely.

Not good.
Please review and advise!!

**Comment by synaptiko** [comment]
I've also noticed this issue and it seems it's bug which is in dm-tool for a very long time (it was reported at 2012-10-02)

https://bugs.launchpad.net/lightdm/+bug/1060228

Now I'm considering replacing LightDM by another manager because current "lock" functionality is like following image:
![](http://media-cache-ec0.pinimg.com/736x/47/33/5f/47335f1ae1aae054e8bc3fc818bee8b4.jpg)

**Comment by dtschmitz** [comment]
If I may a recommendation, and for sake of consistency and standardization, use the same as Fedora, which is gdm.  Yes?  Should be an easy fix.

**Comment by lots0logs** [comment]
This is an issue we are aware of and working on. If your workflow requires a fully secured lock screen, we recommend that you switch to GDM until such time a permanent solution is released. Cheers!

**Comment by dtschmitz** [comment]
P.S.  I love Antergos and want everyone on the developer team to know that you have done an outstanding job.  Keep up the great work.

**Comment by lots0logs** [comment]
Thanks for the support. We appreciate it very much!
