### ISSUE TITLE
Dropbox package version in repositories will be deprecated soon

### ISSUE THREAD

**Issue by JPLeBreton** [Antergos/antergos-packages#468]
Got a notification from the install of Dropbox I got from the repositories, version 62.4.103, that Dropbox would stop working soon if I didn't upgrade. For reference, the version in AUR appears to be 70.4.93-1.

**Comment by killajoe** [comment]
Antergos holds:
pkgver=62.4.103
Out of Date

**Comment by lots0logs** [comment]
I am aware of this. Dropbox is forcing its users to upgrade to a version that will no longer support most linux filesystems. I have purposely not updated the package for that reason. I was hoping Dropbox hadn't implemented a way to force the update but looks like they did. I can't begin to tell you how much I dislike Dropbox due to the way they have handled this entire situation with their Linux users. But I digress. The package will be updated over the weekend.

**Comment by JPLeBreton** [comment]
Ah, this stems from their phasing out everything except ext4 right? That's a bummer.
https://www.dropboxforum.com/t5/Error-messages/Dropbox-client-warns-me-that-it-ll-stop-syncing-in-Nov-why/m-p/290065/highlight/true#M18382

**Comment by jcuenod** [comment]
Is there any reason I still can't see the updated package yet? I see it on https://build.antergos.com/package/dropbox but if I run `aurman -Syu` and then `aurman -S dropbox` I still get:

```
:: The following 1 package(s) are getting reinstalled:
   antergos/dropbox  62.4.103-1            ->  62.4.103-1
```

**Comment by jcuenod** [comment]
Okay, it seems to be working now. I guess that my mirror just synced or something.
